[versions]
agp = "8.12.3"
coilComposeVersion = "2.7.0"
converterGson = "3.0.0"
firebaseBom = "34.5.0"
firebaseBomVersion = "33.5.1"
fragment = "1.8.9"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxCoroutinesPlayServices = "1.10.2"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
material3Version = "1.4.0"
okhttp = "5.3.0"
playServicesTasks = "18.4.0"
poiVersion = "5.4.1"
retrofit = "3.0.0"
services = "4.4.4"
navigationCompose = "2.9.6"
crashlytics = "3.0.6"
zxingAndroidEmbedded = "4.3.0"
runtimeLivedata = "1.9.4"
ui = "1.9.4"
composeMaterial3 = "1.5.5"
uiText = "1.9.4"
material3 = "1.4.0"
foundation = "1.9.4"
exifinterface = "1.4.1"
workRuntimeKtx = "2.11.0"
firebaseFirestoreKtx = "26.0.2"
firebaseAuthKtx = "24.0.1"
firebaseCommonKtx = "22.0.1"



[libraries]

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3-v121 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-navigation-compose = {module = "androidx.navigation:navigation-compose" , version.ref = "navigationCompose"}
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }

apache-poi = { module = "org.apache.poi:poi", version.ref = "poiVersion" }
coil-compose-v250 = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }

com-google-firebase-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
com-google-firebase-firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-bom-v3351 = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
google-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
google-firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
google-firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesTasks" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poiVersion" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "composeMaterial3" }
androidx-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebaseCommonKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }